# Generated by Django 2.2.5 on 2020-06-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech_to_text', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('resulted_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech_to_text.Upload')),
            ],
        ),
    ]
