# Generated by Django 2.2.5 on 2020-06-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech_to_text', '0002_auto_20200602_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
    ]
